queue:
  name: Hosted VS2017
steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: restore
    projects: Src/LeximLibs.sln


- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    projects: Src/LeximLibs.sln


- task: DotNetCoreCLI@2
  displayName: 'dotnet pack'
  inputs:
    command: pack

    packagesToPack: '**/*.csproj'


- task: NuGetCommand@2
  displayName: 'NuGet push'
  inputs:
    command: push

    nuGetFeedType: external

    publishFeedCredentials: 'Nuget.org Public'

